<a href="https://colab.research.google.com/github/pabloga44/TFG/blob/main/cleaner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
! git clone https://github.com/pabloga44/TFG

In [ ]:
open('/content/TFG/main.py','wb')
import main as mn

In [ ]:
def clean_data(x,y):
    # Elimina las filas de NaN y te dice cuales son los parámetros que han dado error
    
    
    nans = [];
    for index in range(len(y)):

      if False in (y[index]==y[index]): #La forma de encontrar un NaN es porque (NaN==NaN)=>False.
        nans.append(index)
        print(x[index])

    for i in nans:
      x = np.delete(x,i,axis=0)
      y = np.delete(y,i,axis=0)

    return x,y

In [ ]:
x = np.loadtxt('/content/TFG/data/Input_all.txt',dtype=float)
y = np.loadtxt('/content/TFG/data/Output_all.txt',dtype=float)

print(x.shape)
print(y.shape,'\n')
      
x,y = clean_data(x,y)

print('\n')
print(x.shape)
print(y.shape)


(23046, 3)
(23046, 8) 

[1.5e-08 2.3e-08 5.2e-01]
[2.7e-08 3.7e-08 5.2e-01]
[2.70e-08 4.10e-08 1.05e+00]
[2.90e-08 4.10e-08 1.05e+00]
[3.1e-08 3.7e-08 5.2e-01]


(23041, 3)
(23041, 8)
